from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
import subprocess
import sys
import unittest
from unittest.mock import patch


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from build_windows_installer import build_installer, main as installer_main


def _prepare_installer_root(root: Path, *, version: str = "3.1.4") -> Path:
    (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
    (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
    (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
    (root / "src" / "fdm" / "version.py").write_text(
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )
    (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text(
        "; stub\n",
        encoding="utf-8",
    )
    return root / "dist" / "installer" / f"fiber-diameter-measurement-setup-{version}.exe"


class BuildWindowsInstallerTests(unittest.TestCase):
    def test_inno_script_requires_release_manifest_and_build_id(self) -> None:
        payload = (PROJECT_ROOT / "packaging" / "inno-setup" / "fdm_installer.iss").read_text(encoding="utf-8")

        self.assertIn('MyAppSourceDir + "\\release-manifest.json"', payload)
        self.assertIn('MyAppSourceDir + "\\build-id.txt"', payload)

    def test_inno_script_registers_only_project_and_digital_slide_associations(self) -> None:
        payload = (PROJECT_ROOT / "packaging" / "inno-setup" / "fdm_installer.iss").read_text(
            encoding="utf-8"
        )

        self.assertIn("ChangesAssociations=yes", payload)
        self.assertIn('Name: "fileassoc"', payload)
        self.assertIn('Flags: checkedonce', payload)
        self.assertIn('LARD.FiberDiameterMeasurement.Project', payload)
        self.assertIn('LARD.FiberDiameterMeasurement.DigitalSlide', payload)
        self.assertIn('Software\\Classes\\.fdmproj\\OpenWithProgids', payload)
        self.assertIn('Software\\Classes\\.fdmslide\\OpenWithProgids', payload)
        self.assertIn('OpenWithProgids"; ValueType: string', payload)
        self.assertIn('SupportedTypes"; ValueType: string', payload)
        self.assertIn('DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}', payload)
        self.assertIn('"""{app}\\{#MyAppExeName}"" ""%1"""', payload)
        self.assertIn("RemoveOwnedExtensionDefault('.fdmproj'", payload)
        self.assertIn("RemoveOwnedExtensionDefault('.fdmslide'", payload)
        for image_suffix in (".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"):
            self.assertNotIn(f'ValueName: "{image_suffix}"', payload)

    def test_sync_only_refreshes_version_auto_include_from_version_py(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "2.4.6"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")

            result = build_installer(root=root, sync_only=True)

            self.assertEqual(result, 0)
            self.assertEqual(
                (root / "packaging" / "inno-setup" / "version.auto.iss").read_text(encoding="utf-8"),
                '; Auto-generated by scripts/build_support.py / build_windows_onedir.py\n#define MyAppVersion "2.4.6"\n',
            )

    def test_build_installer_invokes_compiler_with_iss_script(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "3.1.4"\n', encoding="utf-8")
            iss_path = root / "packaging" / "inno-setup" / "fdm_installer.iss"
            iss_path.write_text("; stub\n", encoding="utf-8")
            expected_output = root / "dist" / "installer" / "fiber-diameter-measurement-setup-3.1.4.exe"

            def compile_installer(*_args, **_kwargs) -> subprocess.CompletedProcess[str]:
                expected_output.parent.mkdir(parents=True, exist_ok=True)
                expected_output.write_bytes(b"installer")
                return subprocess.CompletedProcess([], 0)

            with (
                patch("build_windows_installer.validate_installer_release", return_value=[]) as validate_mock,
                patch("build_windows_installer.subprocess.run", side_effect=compile_installer) as mock_run,
            ):
                result = build_installer(root=root, compiler_path="C:/Tools/ISCC.exe")

            self.assertEqual(result, 0)
            mock_run.assert_called_once_with(
                ["C:/Tools/ISCC.exe", str(iss_path)],
                cwd=root,
                check=True,
            )
            self.assertFalse(validate_mock.call_args.kwargs["strict_asset_hashes"])
            self.assertFalse(validate_mock.call_args.kwargs["strict_release"])
            self.assertIsInstance(validate_mock.call_args.kwargs["warnings"], list)

    def test_cli_rebuilds_onedir_by_default_and_can_explicitly_reuse_it(self) -> None:
        cases = (
            (["build_windows_installer.py"], True),
            (["build_windows_installer.py", "--reuse-onedir"], False),
        )
        for argv, expected_rebuild in cases:
            with (
                self.subTest(argv=argv),
                patch.object(sys, "argv", argv),
                patch("build_windows_installer.build_installer", return_value=0) as build_mock,
            ):
                result = installer_main()

            self.assertEqual(result, 0)
            self.assertEqual(build_mock.call_args.kwargs["rebuild_onedir"], expected_rebuild)
            self.assertFalse(build_mock.call_args.kwargs["strict_release"])

    def test_installer_can_rebuild_missing_onedir_before_compilation(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            expected_output = _prepare_installer_root(root)
            app_dir = root / "dist" / "windows" / "FiberDiameterMeasurement"
            app_dir.rmdir()

            def build_prerequisite(**_kwargs) -> int:
                app_dir.mkdir(parents=True)
                (app_dir / "release-manifest.json").write_text("{}", encoding="utf-8")
                return 0

            def compile_installer(*_args, **_kwargs) -> subprocess.CompletedProcess[str]:
                expected_output.parent.mkdir(parents=True, exist_ok=True)
                expected_output.write_bytes(b"installer")
                return subprocess.CompletedProcess([], 0)

            with (
                patch("build_windows_installer.build_onedir", side_effect=build_prerequisite) as onedir_mock,
                patch("build_windows_installer.validate_installer_release", return_value=[]),
                patch("build_windows_installer.subprocess.run", side_effect=compile_installer),
            ):
                result = build_installer(
                    root=root,
                    compiler_path="C:/Tools/ISCC.exe",
                    rebuild_onedir=True,
                )

            self.assertEqual(result, 0)
            onedir_mock.assert_called_once_with(
                clean=True,
                console=False,
                bootloader_debug=False,
                profile="full",
                strict_asset_hashes=False,
                root=root,
            )

    def test_installer_stops_when_onedir_prerequisite_fails(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _prepare_installer_root(root)

            with (
                patch("build_windows_installer.build_onedir", return_value=1),
                patch("build_windows_installer.validate_installer_release") as validate_mock,
                patch("build_windows_installer.subprocess.run") as run_mock,
            ):
                result = build_installer(
                    root=root,
                    compiler_path="C:/Tools/ISCC.exe",
                    rebuild_onedir=True,
                )

            self.assertEqual(result, 1)
            validate_mock.assert_not_called()
            run_mock.assert_not_called()

    def test_build_installer_can_enable_strict_source_hashes(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _prepare_installer_root(root)

            with (
                patch(
                    "build_windows_installer.validate_installer_release",
                    return_value=["source runtime asset hash mismatch"],
                ) as validate_mock,
                patch("build_windows_installer.subprocess.run") as run_mock,
            ):
                result = build_installer(
                    root=root,
                    compiler_path="C:/Tools/ISCC.exe",
                    strict_asset_hashes=True,
                    strict_release=True,
                )

            self.assertEqual(result, 1)
            self.assertTrue(validate_mock.call_args.kwargs["strict_asset_hashes"])
            self.assertTrue(validate_mock.call_args.kwargs["strict_release"])
            run_mock.assert_not_called()

    def test_build_installer_blocks_when_release_gate_fails(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "3.1.4"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")
            with (
                patch("build_windows_installer.validate_installer_release", return_value=["dirty worktree"]),
                patch("build_windows_installer.subprocess.run") as mock_run,
            ):
                result = build_installer(
                    root=root,
                    compiler_path="C:/Tools/ISCC.exe",
                    strict_release=True,
                )

            self.assertEqual(result, 1)
            mock_run.assert_not_called()

    def test_build_installer_blocks_when_iscc_produces_no_output(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "3.1.4"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")
            stale_output = root / "dist" / "installer" / "fiber-diameter-measurement-setup-3.1.4.exe"
            stale_output.parent.mkdir(parents=True)
            stale_output.write_bytes(b"stale installer")

            with (
                patch("build_windows_installer.validate_installer_release", return_value=[]),
                patch("build_windows_installer.subprocess.run", return_value=subprocess.CompletedProcess([], 0)),
            ):
                result = build_installer(root=root, compiler_path="C:/Tools/ISCC.exe")

            self.assertEqual(result, 1)
            self.assertFalse(stale_output.exists())

    def test_build_installer_blocks_when_iscc_is_unavailable(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "3.1.4"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")

            with (
                patch("build_windows_installer.validate_installer_release", return_value=[]),
                patch("build_windows_installer.find_inno_setup_compiler", return_value=None),
            ):
                result = build_installer(root=root)

            self.assertEqual(result, 2)

    def test_build_installer_runs_optional_sign_and_verify_hooks(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "3.1.4"\n', encoding="utf-8")
            iss_path = root / "packaging" / "inno-setup" / "fdm_installer.iss"
            iss_path.write_text("; stub\n", encoding="utf-8")
            expected_output = root / "dist" / "installer" / "fiber-diameter-measurement-setup-3.1.4.exe"
            commands: list[list[str]] = []

            def run_command(command, **_kwargs) -> subprocess.CompletedProcess[str]:
                commands.append(command)
                if len(commands) == 1:
                    expected_output.parent.mkdir(parents=True, exist_ok=True)
                    expected_output.write_bytes(b"installer")
                return subprocess.CompletedProcess(command, 0)

            with (
                patch("build_windows_installer.validate_installer_release", return_value=[]),
                patch("build_windows_installer.subprocess.run", side_effect=run_command),
            ):
                result = build_installer(
                    root=root,
                    compiler_path="C:/Tools/ISCC.exe",
                    sign_command='signtool sign /fd sha256 "{file}"',
                    verify_signature_command='signtool verify /pa "{file}"',
                )

            self.assertEqual(result, 0)
            self.assertEqual(commands[0], ["C:/Tools/ISCC.exe", str(iss_path)])
            self.assertEqual(commands[1], ["signtool", "sign", "/fd", "sha256", str(expected_output)])
            self.assertEqual(commands[2], ["signtool", "verify", "/pa", str(expected_output)])

    def test_sign_and_verify_commands_require_a_real_file_placeholder(self) -> None:
        cases = (
            ("sign-missing", {"sign_command": "signtool sign /fd sha256"}),
            ("sign-escaped", {"sign_command": 'signtool sign "{{file}}"'}),
            ("sign-invalid-format", {"sign_command": 'signtool sign "{file:{width}}"'}),
            ("verify-missing", {"verify_signature_command": "signtool verify /pa"}),
            ("verify-escaped", {"verify_signature_command": 'signtool verify "{{file}}"'}),
        )
        for label, hook_options in cases:
            with self.subTest(label=label), TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                expected_output = _prepare_installer_root(root)
                commands: list[list[str]] = []

                def run_command(command, **_kwargs) -> subprocess.CompletedProcess[str]:
                    commands.append(command)
                    expected_output.parent.mkdir(parents=True, exist_ok=True)
                    expected_output.write_bytes(b"installer")
                    return subprocess.CompletedProcess(command, 0)

                with (
                    patch("build_windows_installer.validate_installer_release", return_value=[]),
                    patch("build_windows_installer.subprocess.run", side_effect=run_command),
                ):
                    result = build_installer(
                        root=root,
                        compiler_path="C:/Tools/ISCC.exe",
                        **hook_options,
                    )

                self.assertEqual(result, 1)
                self.assertEqual(len(commands), 1, "invalid hooks must not be executed")
                self.assertFalse(expected_output.exists())

    def test_sign_and_verify_process_failures_remove_installer(self) -> None:
        for failing_phase, failing_call in (("sign", 2), ("verify", 3)):
            with self.subTest(phase=failing_phase), TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                expected_output = _prepare_installer_root(root)
                commands: list[list[str]] = []

                def run_command(command, **_kwargs) -> subprocess.CompletedProcess[str]:
                    commands.append(command)
                    if len(commands) == 1:
                        expected_output.parent.mkdir(parents=True, exist_ok=True)
                        expected_output.write_bytes(b"installer")
                    if len(commands) == failing_call:
                        raise subprocess.CalledProcessError(1, command)
                    return subprocess.CompletedProcess(command, 0)

                with (
                    patch("build_windows_installer.validate_installer_release", return_value=[]),
                    patch("build_windows_installer.subprocess.run", side_effect=run_command),
                ):
                    result = build_installer(
                        root=root,
                        compiler_path="C:/Tools/ISCC.exe",
                        sign_command='signtool sign "{file}"',
                        verify_signature_command='signtool verify "{file}"',
                    )

                self.assertEqual(result, 1)
                self.assertEqual(len(commands), failing_call)
                self.assertFalse(expected_output.exists())

    def test_successful_hook_cannot_remove_or_empty_installer(self) -> None:
        for destructive_phase, destructive_call in (("sign", 2), ("verify", 3)):
            with self.subTest(phase=destructive_phase), TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                expected_output = _prepare_installer_root(root)
                commands: list[list[str]] = []

                def run_command(command, **_kwargs) -> subprocess.CompletedProcess[str]:
                    commands.append(command)
                    if len(commands) == 1:
                        expected_output.parent.mkdir(parents=True, exist_ok=True)
                        expected_output.write_bytes(b"installer")
                    elif len(commands) == destructive_call:
                        expected_output.write_bytes(b"")
                    return subprocess.CompletedProcess(command, 0)

                with (
                    patch("build_windows_installer.validate_installer_release", return_value=[]),
                    patch("build_windows_installer.subprocess.run", side_effect=run_command),
                ):
                    result = build_installer(
                        root=root,
                        compiler_path="C:/Tools/ISCC.exe",
                        sign_command='signtool sign "{file}"',
                        verify_signature_command='signtool verify "{file}"',
                    )

                self.assertEqual(result, 1)
                self.assertEqual(len(commands), destructive_call)
                self.assertFalse(expected_output.exists())

    def test_build_installer_requires_existing_onedir_output(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "1.0.1"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")

            result = build_installer(root=root, compiler_path="C:/Tools/ISCC.exe")

            self.assertEqual(result, 1)


if __name__ == "__main__":
    unittest.main()
