from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
import subprocess
import sys
import unittest
from unittest.mock import patch


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from build_windows_installer import build_installer


class BuildWindowsInstallerTests(unittest.TestCase):
    def test_sync_only_refreshes_version_auto_include_from_version_py(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "2.4.6"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")

            result = build_installer(root=root, sync_only=True)

            self.assertEqual(result, 0)
            self.assertEqual(
                (root / "packaging" / "inno-setup" / "version.auto.iss").read_text(encoding="utf-8"),
                '; Auto-generated by scripts/build_support.py / build_windows_onedir.py\n#define MyAppVersion "2.4.6"\n',
            )

    def test_build_installer_invokes_compiler_with_iss_script(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "dist" / "windows" / "FiberDiameterMeasurement").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "3.1.4"\n', encoding="utf-8")
            iss_path = root / "packaging" / "inno-setup" / "fdm_installer.iss"
            iss_path.write_text("; stub\n", encoding="utf-8")

            with patch("build_windows_installer.subprocess.run") as mock_run:
                result = build_installer(root=root, compiler_path="C:/Tools/ISCC.exe")

            self.assertEqual(result, 0)
            mock_run.assert_called_once_with(
                ["C:/Tools/ISCC.exe", str(iss_path)],
                cwd=root,
                check=True,
            )

    def test_build_installer_requires_existing_onedir_output(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "1.0.1"\n', encoding="utf-8")
            (root / "packaging" / "inno-setup" / "fdm_installer.iss").write_text("; stub\n", encoding="utf-8")

            result = build_installer(root=root, compiler_path="C:/Tools/ISCC.exe")

            self.assertEqual(result, 1)


if __name__ == "__main__":
    unittest.main()
