from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
import hashlib
import json
import subprocess
import sys
import tomllib
import unittest
from unittest.mock import patch


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from fdm import __version__
from build_support import (
    check_runtime_profile,
    collect_private_content_template_datas,
    collect_runtime_datas,
    get_dirty_worktree_entries,
    read_app_version,
    resolve_runtime_profile,
    runtime_profile_asset_metadata,
    runtime_profile_required_files,
    should_include_runtime_file,
    validate_installer_release,
    write_installer_version_include,
    write_release_manifest,
)
from fdm.release_manifest import packaged_runtime_features, verify_release_manifest


def _create_release_fixture(root: Path) -> tuple[Path, tuple[str, ...]]:
    (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
    (root / "src" / "fdm" / "version.py").write_text('__version__ = "9.8.7"\n', encoding="utf-8")
    config_payload = (PROJECT_ROOT / "runtime_assets.toml").read_bytes()
    (root / "runtime_assets.toml").write_bytes(config_payload)
    required = runtime_profile_required_files(root, "core")
    app_dir = root / "dist" / "windows" / "FiberDiameterMeasurement"
    for token in required:
        source = root / token
        packaged = app_dir / token
        source.parent.mkdir(parents=True, exist_ok=True)
        packaged.parent.mkdir(parents=True, exist_ok=True)
        payload = (PROJECT_ROOT / token).read_bytes()
        source.write_bytes(payload)
        packaged.write_bytes(payload)
    app_dir.mkdir(parents=True, exist_ok=True)
    (app_dir / "FiberDiameterMeasurement.exe").write_bytes(b"main")
    (app_dir / "FiberAreaWorker.exe").write_bytes(b"worker")
    (app_dir / "runtime_assets.toml").write_bytes(config_payload)
    write_release_manifest(
        app_dir,
        root,
        profile="core",
        clean_build=True,
        build_id="build-123",
        source_commit="abc123",
        source_dirty_entries=[],
    )
    return app_dir, required


class BuildSupportTests(unittest.TestCase):
    def test_read_app_version_matches_runtime_version(self) -> None:
        self.assertEqual(read_app_version(PROJECT_ROOT), __version__)

    def test_write_installer_version_include_uses_app_version(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "9.8.7"\n', encoding="utf-8")

            output = write_installer_version_include(root)

            self.assertEqual(output, root / "packaging" / "inno-setup" / "version.auto.iss")
            self.assertEqual(
                output.read_text(encoding="utf-8"),
                '; Auto-generated by scripts/build_support.py / build_windows_onedir.py\n#define MyAppVersion "9.8.7"\n',
            )

    def test_committed_installer_version_include_matches_app_version(self) -> None:
        payload = (PROJECT_ROOT / "packaging" / "inno-setup" / "version.auto.iss").read_text(encoding="utf-8")
        self.assertIn(f'#define MyAppVersion "{__version__}"', payload)

    def test_runtime_filter_excludes_packaging_noise_from_area_infer(self) -> None:
        runtime_root = PROJECT_ROOT / "runtime"
        excluded = [
            runtime_root / "area-infer" / ".dockerignore",
            runtime_root / "area-infer" / "Dockerfile",
            runtime_root / "area-infer" / "tests" / "test_engine_device.py",
            runtime_root / "area-infer" / "app" / "__pycache__" / "engine.cpython-314.pyc",
            runtime_root / "area-infer" / "vendor" / "yolact" / "README.md",
            runtime_root / "area-infer" / "vendor" / "yolact" / "web" / "index.html",
            runtime_root / "area-infer" / "vendor" / "yolact" / "scripts" / "eval.sh",
            runtime_root / "area-infer" / "vendor" / "yolact" / "train.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "eval.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "run_coco_eval.py",
            runtime_root / "area-models" / "b_c1_1.3(++).pth",
            runtime_root / "area-models" / "b_c1_1.3(old).pth",
            runtime_root / "segment-anything" / "light_hq_sam" / "sam_hq_vit_tiny.pth",
            runtime_root / "segment-anything" / "efficient_sam_s" / "efficient_sam_vits.pt",
            runtime_root / "reference-instance" / "matcher" / "models" / "sam_vit_h_4b8939.pth",
            runtime_root / "content-templates" / "sheet.xlt",
        ]
        included = [
            runtime_root / "area-infer" / "app" / "engine.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "data" / "config.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "data" / "grid.npy",
            runtime_root / "area-models" / "b_v1_1.3.pth",
            runtime_root / "segment-anything" / "edge_sam" / "edge_sam_encoder.onnx",
            runtime_root / "segment-anything" / "edge_sam_3x" / "edge_sam_3x_encoder.onnx",
        ]

        for path in excluded:
            self.assertFalse(should_include_runtime_file(path, runtime_root), path.as_posix())
        for path in included:
            self.assertTrue(should_include_runtime_file(path, runtime_root), path.as_posix())

    def test_collect_runtime_datas_omits_area_infer_docker_tests_and_pycache(self) -> None:
        datas = collect_runtime_datas(PROJECT_ROOT)
        collected = {Path(src).resolve() for src, _ in datas}

        self.assertIn((PROJECT_ROOT / "runtime" / "area-infer" / "app" / "engine.py").resolve(), collected)
        self.assertIn((PROJECT_ROOT / "runtime" / "segment-anything" / "edge_sam" / "edge_sam_encoder.onnx").resolve(), collected)
        self.assertIn((PROJECT_ROOT / "runtime" / "segment-anything" / "edge_sam_3x" / "edge_sam_3x_encoder.onnx").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / ".dockerignore").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "Dockerfile").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "tests" / "test_engine_device.py").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "vendor" / "yolact" / "train.py").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "vendor" / "yolact" / "eval.py").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "segment-anything" / "light_hq_sam" / "sam_hq_vit_tiny.pth").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "segment-anything" / "efficient_sam_s" / "efficient_sam_vits.pt").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "reference-instance" / "matcher" / "models" / "sam_vit_h_4b8939.pth").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-models" / "b_c1_1.3(++).pth").resolve(), collected)

    def test_private_content_templates_are_collected_without_public_asset_metadata(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            templates = root / "runtime" / "content-templates"
            (templates / "nested").mkdir(parents=True)
            (templates / "sheet.xlt").write_bytes(b"private")
            (templates / "nested" / "record.xlsm").write_bytes(b"private")
            (templates / ".DS_Store").write_bytes(b"noise")
            datas = collect_private_content_template_datas(root)
            collected = {
                Path(source).relative_to(root).as_posix(): target
                for source, target in datas
            }

        self.assertEqual(
            collected,
            {
                "runtime/content-templates/nested/record.xlsm": "runtime/content-templates/nested",
                "runtime/content-templates/sheet.xlt": "runtime/content-templates",
            },
        )
        self.assertFalse(
            any(
                record.source.startswith("runtime/content-templates/")
                for record in runtime_profile_asset_metadata(PROJECT_ROOT, "full")
            )
        )

    def test_area_models_can_be_excluded_without_leaking_the_feature(self) -> None:
        datas = collect_runtime_datas(
            PROJECT_ROOT,
            "full",
            strict_asset_hashes=False,
            excluded_groups=("area-models",),
        )
        collected = {
            Path(source).relative_to(PROJECT_ROOT).as_posix()
            for source, _target in datas
        }
        profile = resolve_runtime_profile(
            PROJECT_ROOT,
            "full",
            excluded_groups=("area-models",),
        )

        self.assertFalse(any(path.startswith("runtime/area-models/") for path in collected))
        self.assertIn("runtime/area-infer/app/engine.py", collected)
        self.assertNotIn("area-inference", profile.features)
        self.assertIn("magic-segmentation", profile.features)

    def test_runtime_profiles_keep_core_small_and_full_complete(self) -> None:
        core = {Path(source).relative_to(PROJECT_ROOT).as_posix() for source, _ in collect_runtime_datas(PROJECT_ROOT, "core")}
        full = {Path(source).relative_to(PROJECT_ROOT).as_posix() for source, _ in collect_runtime_datas(PROJECT_ROOT, "full")}

        self.assertIn("runtime/camera/microview/x64/MVAPI.dll", core)
        self.assertNotIn("runtime/area-models/b_v1_1.3.pth", core)
        self.assertIn("runtime/area-models/b_v1_1.3.pth", full)
        self.assertIn("runtime/area-infer/app/model_metadata.py", full)
        self.assertFalse(any(path.startswith("runtime/content-templates/") for path in core | full))
        profile_check = check_runtime_profile(PROJECT_ROOT, "full")
        self.assertIn("measurement", resolve_runtime_profile(PROJECT_ROOT, "core").features)
        self.assertIn("area-inference", resolve_runtime_profile(PROJECT_ROOT, "full").features)
        self.assertEqual(profile_check.missing_files, ())
        self.assertEqual(profile_check.hash_mismatches, ())
        self.assertEqual(profile_check.metadata_errors, ())

    def test_full_profile_required_assets_have_complete_authoritative_metadata(self) -> None:
        records = runtime_profile_asset_metadata(PROJECT_ROOT, "full")
        config = tomllib.loads((PROJECT_ROOT / "runtime_assets.toml").read_text(encoding="utf-8"))

        self.assertEqual(len(records), 57)
        self.assertEqual(len(records), len(config["assets"]))
        self.assertEqual({record.target for record in records}, set(runtime_profile_required_files(PROJECT_ROOT, "full")))
        self.assertTrue({"microview", "area-infer", "area-models", "segment-anything"}.issubset(
            {record.group for record in records}
        ))
        for record in records:
            with self.subTest(source=record.source):
                source_path = PROJECT_ROOT / record.source
                self.assertTrue(record.required)
                self.assertTrue(record.feature)
                self.assertTrue(record.license)
                self.assertNotIn("runtime/content-templates/", record.source)
                self.assertNotIn("runtime/content-templates/", record.target)
                self.assertEqual(source_path.stat().st_size, record.size)
                self.assertEqual(hashlib.sha256(source_path.read_bytes()).hexdigest(), record.sha256)

    def test_runtime_profile_reports_missing_or_incomplete_required_file_metadata(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "runtime_assets.toml").write_text(
                """\
schema_version = 1
assets = []
[release]
ignored_untracked_prefixes = []
[profiles.core]
groups = ["model"]
required_python_modules = []
[groups.model]
root = "runtime/models"
filter = "all"
required_files = ["runtime/models/model.bin"]
""",
                encoding="utf-8",
            )

            check = check_runtime_profile(root, "core")

            self.assertFalse(check.ok)
            self.assertTrue(any("missing complete asset metadata" in error for error in check.metadata_errors))

    def test_runtime_profile_rejects_content_template_and_incomplete_license_metadata(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            asset = root / "runtime" / "content-templates" / "sheet.xlt"
            asset.parent.mkdir(parents=True)
            asset.write_bytes(b"template")
            digest = hashlib.sha256(asset.read_bytes()).hexdigest()
            (root / "runtime_assets.toml").write_text(
                f"""\
schema_version = 1
[release]
ignored_untracked_prefixes = ["runtime/content-templates/"]
[profiles.core]
groups = ["templates"]
required_python_modules = []
[groups.templates]
root = "runtime/content-templates"
filter = "all"
required_files = ["runtime/content-templates/sheet.xlt"]
[[assets]]
source = "runtime/content-templates/sheet.xlt"
target = "runtime/content-templates/sheet.xlt"
group = "templates"
feature = "measurement"
required = true
size = 8
sha256 = "{digest}"
license = ""
""",
                encoding="utf-8",
            )

            check = check_runtime_profile(root, "core")

            self.assertFalse(check.ok)
            self.assertTrue(any("missing license metadata" in error for error in check.metadata_errors))
            self.assertTrue(any("must not be a release asset" in error for error in check.metadata_errors))

    def test_runtime_profile_blocks_asset_with_unexpected_pinned_hash(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            asset = root / "runtime" / "models" / "model.bin"
            asset.parent.mkdir(parents=True)
            asset.write_bytes(b"unexpected")
            (root / "runtime_assets.toml").write_text(
                """\
schema_version = 1
[release]
ignored_untracked_prefixes = []
[profiles.core]
groups = ["model"]
required_python_modules = []
[groups.model]
root = "runtime/models"
filter = "all"
required_files = ["runtime/models/model.bin"]
[[assets]]
source = "runtime/models/model.bin"
target = "runtime/models/model.bin"
group = "model"
feature = "measurement"
required = true
size = 10
sha256 = "0000000000000000000000000000000000000000000000000000000000000000"
license = "LicenseRef-Test"
""",
                encoding="utf-8",
            )

            check = check_runtime_profile(root, "core")

            self.assertFalse(check.ok)
            self.assertEqual(len(check.hash_mismatches), 1)
            self.assertIn("runtime/models/model.bin", check.hash_mismatches[0])
            with self.assertRaisesRegex(RuntimeError, "failed asset preflight"):
                collect_runtime_datas(root, "core")
            self.assertEqual(
                collect_runtime_datas(root, "core", strict_asset_hashes=False),
                [(str(asset), "runtime/models")],
            )

    def test_runtime_asset_target_controls_packaged_destination(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            asset = root / "runtime" / "source" / "model.bin"
            asset.parent.mkdir(parents=True)
            asset.write_bytes(b"model")
            digest = hashlib.sha256(asset.read_bytes()).hexdigest()
            (root / "runtime_assets.toml").write_text(
                f"""\
schema_version = 1
[release]
ignored_untracked_prefixes = []
[profiles.core]
groups = ["model"]
required_python_modules = []
[groups.model]
root = "runtime/source"
filter = "all"
required_files = ["runtime/source/model.bin"]
[[assets]]
source = "runtime/source/model.bin"
target = "runtime/packaged/model.bin"
group = "model"
feature = "measurement"
required = true
size = 5
sha256 = "{digest}"
license = "LicenseRef-Test"
""",
                encoding="utf-8",
            )

            self.assertEqual(runtime_profile_required_files(root, "core"), ("runtime/packaged/model.bin",))
            self.assertEqual(
                collect_runtime_datas(root, "core"),
                [(str(asset), "runtime/packaged")],
            )
            self.assertTrue(check_runtime_profile(root, "core").ok)

    def test_dirty_gate_ignores_generated_outputs_and_untracked_content_templates_only(self) -> None:
        output = (
            "?? runtime/content-templates/sheet.xlt\0"
            "?? dist/windows/app.exe\0"
            "?? build/pyinstaller/cache.bin\0"
            "?? docs/-面积法-定量试验原始记录-新系统.txt\0"
            " M src/fdm/app.py\0"
        ).encode("utf-8")
        completed = subprocess.CompletedProcess(
            [],
            0,
            stdout=output,
            stderr=b"",
        )

        with patch("build_support.subprocess.run", return_value=completed) as run_mock:
            entries = get_dirty_worktree_entries(PROJECT_ROOT)

        self.assertEqual(entries, ["?? docs/-面积法-定量试验原始记录-新系统.txt", " M src/fdm/app.py"])
        self.assertFalse(run_mock.call_args.kwargs["text"])

    def test_release_manifest_detects_hash_build_id_and_stale_commit_mismatches(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app_dir, required = _create_release_fixture(root)

            valid = verify_release_manifest(
                app_dir,
                expected_profile="core",
                expected_version="9.8.7",
                expected_commit="abc123",
                require_clean_source=True,
                require_clean_build=True,
                reject_extra_files=True,
            )
            self.assertTrue(valid["ok"], valid["errors"])
            self.assertEqual(set(valid["features"]), {"measurement", "capture", "digital-slide"})
            self.assertEqual(packaged_runtime_features(app_dir), frozenset(valid["features"]))
            self.assertIn("python", valid["dependency_versions"])
            self.assertIn("tifffile", valid["dependency_versions"])

            first_asset = app_dir / required[0]
            first_asset.write_bytes(b"tampered")
            tampered = verify_release_manifest(app_dir)
            self.assertFalse(tampered["ok"])
            self.assertTrue(any("sha256 mismatch" in error or "size mismatch" in error for error in tampered["errors"]))
            first_asset.write_bytes((root / required[0]).read_bytes())

            (app_dir / "build-id.txt").write_text("different\n", encoding="utf-8")
            wrong_build = verify_release_manifest(app_dir)
            self.assertTrue(any("build-id mismatch" in error for error in wrong_build["errors"]))

            stale = verify_release_manifest(app_dir, expected_commit="new-commit")
            self.assertTrue(any("stale dist" in error for error in stale["errors"]))

    def test_release_manifest_json_is_strict_and_inventory_is_complete(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app_dir, _required = _create_release_fixture(root)
            manifest = json.loads((app_dir / "release-manifest.json").read_text(encoding="utf-8"))
            paths = {entry["path"] for entry in manifest["files"]}

            self.assertIn("FiberDiameterMeasurement.exe", paths)
            self.assertIn("FiberAreaWorker.exe", paths)
            self.assertIn("build-id.txt", paths)
            self.assertIn("runtime_assets.toml", paths)
            self.assertNotIn("release-manifest.json", paths)

    def test_release_manifest_records_and_enforces_private_component_selection(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app_dir, _required = _create_release_fixture(root)
            template = app_dir / "runtime" / "content-templates" / "internal.xlsm"
            template.parent.mkdir(parents=True)
            template.write_bytes(b"private template")
            write_release_manifest(
                app_dir,
                root,
                profile="core",
                clean_build=True,
                build_id="build-private",
                source_commit="abc123",
                source_dirty_entries=[],
                included_components=("content-templates",),
            )

            included = verify_release_manifest(
                app_dir,
                expected_excluded_components=(),
                expected_included_components=("content-templates",),
            )
            self.assertTrue(included["ok"], included["errors"])

            write_release_manifest(
                app_dir,
                root,
                profile="core",
                clean_build=True,
                build_id="build-excluded",
                source_commit="abc123",
                source_dirty_entries=[],
                excluded_components=("content-templates",),
            )
            invalid_exclusion = verify_release_manifest(app_dir)

            self.assertFalse(invalid_exclusion["ok"])
            self.assertTrue(
                any("excluded component is present" in error for error in invalid_exclusion["errors"])
            )

    def test_installer_gate_blocks_dirty_tree_and_runtime_asset_changed_after_build(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app_dir, required = _create_release_fixture(root)
            with (
                patch("build_support.get_git_commit", return_value="abc123"),
                patch("build_support.get_dirty_worktree_entries", return_value=[]),
            ):
                self.assertEqual(validate_installer_release(root, app_dir, profile="core"), [])

            (root / required[0]).write_bytes(b"source changed after build")
            with (
                patch("build_support.get_git_commit", return_value="abc123"),
                patch("build_support.get_dirty_worktree_entries", return_value=[" M src/fdm/app.py"]),
            ):
                errors = validate_installer_release(root, app_dir, profile="core")

            self.assertTrue(any("dirty worktree" in error for error in errors))
            self.assertTrue(any("stale dist runtime asset" in error for error in errors))

    def test_installer_gate_can_warn_instead_of_blocking_on_pinned_source_hashes(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app_dir, required = _create_release_fixture(root)
            changed_payload = b"internal build asset\n"
            (root / required[0]).write_bytes(changed_payload)
            (app_dir / required[0]).write_bytes(changed_payload)
            write_release_manifest(
                app_dir,
                root,
                profile="core",
                clean_build=True,
                build_id="build-123",
                source_commit="abc123",
                source_dirty_entries=[],
            )
            warnings: list[str] = []
            with (
                patch("build_support.get_git_commit", return_value="abc123"),
                patch("build_support.get_dirty_worktree_entries", return_value=[]),
            ):
                strict_errors = validate_installer_release(root, app_dir, profile="core")
                relaxed_errors = validate_installer_release(
                    root,
                    app_dir,
                    profile="core",
                    strict_asset_hashes=False,
                    warnings=warnings,
                )

            self.assertTrue(any("source runtime asset hash mismatch" in error for error in strict_errors))
            self.assertEqual(relaxed_errors, [])
            self.assertTrue(any("source runtime asset hash mismatch" in warning for warning in warnings))

    def test_internal_installer_gate_warns_instead_of_blocking_on_dirty_source(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app_dir, _required = _create_release_fixture(root)
            write_release_manifest(
                app_dir,
                root,
                profile="core",
                clean_build=True,
                build_id="build-123",
                source_commit="abc123",
                source_dirty_entries=[" M src/fiber_diameter_measurement.egg-info/SOURCES.txt"],
            )
            warnings: list[str] = []
            with (
                patch("build_support.get_git_commit", return_value="abc123"),
                patch(
                    "build_support.get_dirty_worktree_entries",
                    return_value=[" M src/fiber_diameter_measurement.egg-info/SOURCES.txt"],
                ),
            ):
                errors = validate_installer_release(
                    root,
                    app_dir,
                    profile="core",
                    strict_release=False,
                    warnings=warnings,
                )

            self.assertEqual(errors, [])
            self.assertTrue(any("dirty worktree" in warning for warning in warnings))


if __name__ == "__main__":
    unittest.main()
