from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
import sys
import unittest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from fdm import __version__
from build_support import collect_runtime_datas, read_app_version, should_include_runtime_file, write_installer_version_include


class BuildSupportTests(unittest.TestCase):
    def test_read_app_version_matches_runtime_version(self) -> None:
        self.assertEqual(read_app_version(PROJECT_ROOT), __version__)

    def test_write_installer_version_include_uses_app_version(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "src" / "fdm").mkdir(parents=True, exist_ok=True)
            (root / "packaging" / "inno-setup").mkdir(parents=True, exist_ok=True)
            (root / "src" / "fdm" / "version.py").write_text('__version__ = "9.8.7"\n', encoding="utf-8")

            output = write_installer_version_include(root)

            self.assertEqual(output, root / "packaging" / "inno-setup" / "version.auto.iss")
            self.assertEqual(
                output.read_text(encoding="utf-8"),
                '; Auto-generated by scripts/build_support.py / build_windows_onedir.py\n#define MyAppVersion "9.8.7"\n',
            )

    def test_committed_installer_version_include_matches_app_version(self) -> None:
        payload = (PROJECT_ROOT / "packaging" / "inno-setup" / "version.auto.iss").read_text(encoding="utf-8")
        self.assertIn(f'#define MyAppVersion "{__version__}"', payload)

    def test_runtime_filter_excludes_packaging_noise_from_area_infer(self) -> None:
        runtime_root = PROJECT_ROOT / "runtime"
        excluded = [
            runtime_root / "area-infer" / ".dockerignore",
            runtime_root / "area-infer" / "Dockerfile",
            runtime_root / "area-infer" / "tests" / "test_engine_device.py",
            runtime_root / "area-infer" / "app" / "__pycache__" / "engine.cpython-314.pyc",
            runtime_root / "area-infer" / "vendor" / "yolact" / "README.md",
            runtime_root / "area-infer" / "vendor" / "yolact" / "web" / "index.html",
            runtime_root / "area-infer" / "vendor" / "yolact" / "scripts" / "eval.sh",
            runtime_root / "area-infer" / "vendor" / "yolact" / "train.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "eval.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "run_coco_eval.py",
        ]
        included = [
            runtime_root / "area-infer" / "app" / "engine.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "data" / "config.py",
            runtime_root / "area-infer" / "vendor" / "yolact" / "data" / "grid.npy",
            runtime_root / "area-models" / "b_v1_1.3.pth",
            runtime_root / "segment-anything" / "edge_sam" / "edge_sam_encoder.onnx",
        ]

        for path in excluded:
            self.assertFalse(should_include_runtime_file(path, runtime_root), path.as_posix())
        for path in included:
            self.assertTrue(should_include_runtime_file(path, runtime_root), path.as_posix())

    def test_collect_runtime_datas_omits_area_infer_docker_tests_and_pycache(self) -> None:
        datas = collect_runtime_datas(PROJECT_ROOT)
        collected = {Path(src).resolve() for src, _ in datas}

        self.assertIn((PROJECT_ROOT / "runtime" / "area-infer" / "app" / "engine.py").resolve(), collected)
        self.assertIn((PROJECT_ROOT / "runtime" / "segment-anything" / "edge_sam" / "edge_sam_encoder.onnx").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / ".dockerignore").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "Dockerfile").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "tests" / "test_engine_device.py").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "vendor" / "yolact" / "train.py").resolve(), collected)
        self.assertNotIn((PROJECT_ROOT / "runtime" / "area-infer" / "vendor" / "yolact" / "eval.py").resolve(), collected)


if __name__ == "__main__":
    unittest.main()
