from __future__ import annotations

from pathlib import Path
import re


_VERSION_PATTERN = re.compile(r'^__version__\s*=\s*["\']([^"\']+)["\']', re.MULTILINE)
_COMMON_SKIP_NAMES = {
    ".dockerignore",
    ".DS_Store",
    ".gitignore",
    "Dockerfile",
    "environment.yml",
    "README.md",
    "CHANGELOG.md",
}
_COMMON_SKIP_SUFFIXES = {".pyc", ".pyo"}
_COMMON_SKIP_PARTS = {"__pycache__", "tests"}
_AREA_INFER_SKIP_NAMES = {
    "eval.py",
    "run_coco_eval.py",
    "train.py",
}
PACKAGED_AREA_MODEL_FILENAMES = frozenset(
    {
        "b_v1_1.3.pth",
        "b_cv_1.3.pth",
        "b_c1_1.3.pth",
        "b_cm_1.3.pth",
        "b_cc_1.3.pth",
        "b_cvlm_1.3.pth",
    }
)
PACKAGED_SEGMENT_ANYTHING_DIRS = frozenset({"edge_sam", "edge_sam_3x"})
PACKAGED_SEGMENT_ANYTHING_FILENAMES = frozenset(
    {
        "edge_sam_encoder.onnx",
        "edge_sam_decoder.onnx",
        "edge_sam_3x_encoder.onnx",
        "edge_sam_3x_decoder.onnx",
    }
)


def read_app_version(project_root: Path) -> str:
    version_file = project_root / "src" / "fdm" / "version.py"
    payload = version_file.read_text(encoding="utf-8")
    match = _VERSION_PATTERN.search(payload)
    if match is None:
        raise RuntimeError(f"Unable to parse app version from {version_file}")
    return match.group(1).strip()


def write_installer_version_include(project_root: Path) -> Path:
    version = read_app_version(project_root)
    output = project_root / "packaging" / "inno-setup" / "version.auto.iss"
    output.write_text(
        (
            "; Auto-generated by scripts/build_support.py / build_windows_onedir.py\n"
            f'#define MyAppVersion "{version}"\n'
        ),
        encoding="utf-8",
    )
    return output


def _should_skip_common(file_path: Path) -> bool:
    if file_path.name.startswith("._"):
        return True
    if file_path.name in _COMMON_SKIP_NAMES:
        return True
    if file_path.suffix in _COMMON_SKIP_SUFFIXES:
        return True
    if any(part in _COMMON_SKIP_PARTS for part in file_path.parts):
        return True
    return False


def _should_include_area_infer(relative_path: Path) -> bool:
    parts = relative_path.parts
    if len(parts) < 2:
        return False
    section = parts[1]
    if section == "app":
        return relative_path.suffix == ".py"
    if section != "vendor" or len(parts) < 4 or parts[2] != "yolact":
        return False
    vendor_parts = parts[3:]
    if not vendor_parts:
        return False
    if vendor_parts[0] in {"web", "scripts", "external"}:
        return False
    if vendor_parts[0] == "data" and len(vendor_parts) > 1 and vendor_parts[1] == "scripts":
        return False
    if relative_path.name in _AREA_INFER_SKIP_NAMES:
        return False
    if relative_path.name in _COMMON_SKIP_NAMES:
        return False
    if relative_path.suffix in {".md", ".sh", ".html", ".css", ".js", ".json", ".png"}:
        return False
    if relative_path.name == "LICENSE":
        return True
    return relative_path.suffix in {".py", ".pyx", ".npy"}


def _should_include_segment_anything(relative_path: Path) -> bool:
    parts = relative_path.parts
    if len(parts) != 3:
        return False
    if parts[1] not in PACKAGED_SEGMENT_ANYTHING_DIRS:
        return False
    return relative_path.name in PACKAGED_SEGMENT_ANYTHING_FILENAMES


def _should_include_area_model(relative_path: Path) -> bool:
    parts = relative_path.parts
    if len(parts) != 2:
        return False
    return relative_path.name in PACKAGED_AREA_MODEL_FILENAMES


def should_include_runtime_file(file_path: Path, runtime_root: Path) -> bool:
    if _should_skip_common(file_path):
        return False
    relative_path = file_path.relative_to(runtime_root)
    if not relative_path.parts:
        return False
    if relative_path.parts[0] == "area-infer":
        return _should_include_area_infer(relative_path)
    if relative_path.parts[0] == "segment-anything":
        return _should_include_segment_anything(relative_path)
    if relative_path.parts[0] == "area-models":
        return _should_include_area_model(relative_path)
    if relative_path.parts[0] == "reference-instance":
        return False
    return True


def collect_runtime_datas(project_root: Path) -> list[tuple[str, str]]:
    runtime_root = project_root / "runtime"
    collected: list[tuple[str, str]] = []
    if not runtime_root.exists():
        return collected
    for file_path in runtime_root.rglob("*"):
        if not file_path.is_file():
            continue
        if not should_include_runtime_file(file_path, runtime_root):
            continue
        target_dir = file_path.parent.relative_to(project_root)
        collected.append((str(file_path), str(target_dir)))
    return collected
